// LOW CONFIDENCE: This map was seeded from a partial third-party source.
// IMPORTANT: After first live getRooms() call, log listing.listingAmenities to discover actual IDs.
// Add any missing IDs here. Hot Tub, Water View, Balcony IDs are unknown until live data.
// Source: partial list from lymebayescapes.co.uk/hostaway-listing-amenities/ [LOW confidence]

export const AMENITY_NAMES: Record<number, string> = {
  2: 'Internet',
  3: 'WiFi',
  7: 'Kitchen',
  8: 'Fireplace',
  9: 'Washer',
  10: 'Dryer',
  11: 'Air Conditioning',
  12: 'Heating',
  13: 'Washer',
  14: 'Dryer',
  15: 'Smoke Detector',
  16: 'Carbon Monoxide Detector',
  17: 'Hair Dryer',
  18: 'Heating',
  19: 'Iron',
  20: 'TV',
  21: 'Cable TV',
  22: 'Pool',
  23: 'Gym',
  24: 'Elevator',
  25: 'Indoor Fireplace',
  26: 'Buzzer / Wireless Intercom',
  27: 'Doorman',
  28: 'Shampoo',
  29: 'Hangers',
  30: 'Laptop-Friendly Workspace',
  31: 'Family/Kid Friendly',
  32: 'Suitable for Events',
  33: 'Smoking Allowed',
  34: 'Pets Allowed',
  35: 'First Aid Kit',
  36: 'Safety Card',
  37: 'Fire Extinguisher',
  38: 'Wheelchair Accessible',
  39: 'Elevator',
  40: 'Wide Hallway Clearance',
  41: 'Wide Doorway',
  42: 'Bed Linens',
  43: 'Extra Pillows and Blankets',
  44: 'Microwave',
  45: 'Coffee Maker',
  46: 'Refrigerator',
  47: 'Dishwasher',
  48: 'Dishes and Silverware',
  49: 'Cooking Basics',
  50: 'Oven',
  51: 'Stove',
  52: 'BBQ Grill',
  53: 'Patio or Balcony',
  54: 'Garden or Backyard',
  55: 'Beach Front',
  56: 'Waterfront',
  57: 'Lake Access',
  58: 'Ski-in / Ski-out',
  59: 'Beach Access',
  // Unknown IDs — must verify from live API data:
  // Hot Tub: amenityId unknown
  // Water View: amenityId unknown
  // Balcony: amenityId unknown (may overlap with ID 53 "Patio or Balcony")
};
